// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnDOzQQlKsQoN1iK17W6GzicdB7yQbhk',
    appId: '1:339349232348:web:6524c34054fa5df8d07219',
    messagingSenderId: '339349232348',
    projectId: 'bionicbean-be5d8',
    authDomain: 'bionicbean-be5d8.firebaseapp.com',
    storageBucket: 'bionicbean-be5d8.appspot.com',
    measurementId: 'G-J24L9PLQK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWHbAilJO_Gw9v-ClZ_p1ue7IpZT3CaA',
    appId: '1:339349232348:android:a188f2aa6e5c0ca0d07219',
    messagingSenderId: '339349232348',
    projectId: 'bionicbean-be5d8',
    storageBucket: 'bionicbean-be5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdKhYh6M35KWzuHy1LROBvxjcYXwjjh9s',
    appId: '1:339349232348:ios:71b4579651cac990d07219',
    messagingSenderId: '339349232348',
    projectId: 'bionicbean-be5d8',
    storageBucket: 'bionicbean-be5d8.appspot.com',
    iosBundleId: 'com.example.beanApp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdKhYh6M35KWzuHy1LROBvxjcYXwjjh9s',
    appId: '1:339349232348:ios:10a7df30e24dd72cd07219',
    messagingSenderId: '339349232348',
    projectId: 'bionicbean-be5d8',
    storageBucket: 'bionicbean-be5d8.appspot.com',
    iosBundleId: 'com.example.beanApp0.RunnerTests',
  );
}
