// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRnjVLgsF3y8oqnXOFJqTjus7E6bn8wM',
    appId: '1:788870623427:web:3725a4df0cc134d1d07276',
    messagingSenderId: '788870623427',
    projectId: 'bionicbean0',
    authDomain: 'bionicbean0.firebaseapp.com',
    storageBucket: 'bionicbean0.appspot.com',
    measurementId: 'G-3RQB517BXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALgaPqvCCZo128EcYJcaYos9-uWc2wKCc',
    appId: '1:788870623427:android:3ebfa39c7b029c01d07276',
    messagingSenderId: '788870623427',
    projectId: 'bionicbean0',
    storageBucket: 'bionicbean0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyUYpycIpFp2NCT5oYNHyzCR5v86wB8xM',
    appId: '1:788870623427:ios:019e21f896efcdd9d07276',
    messagingSenderId: '788870623427',
    projectId: 'bionicbean0',
    storageBucket: 'bionicbean0.appspot.com',
    iosBundleId: 'com.example.beanApp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyUYpycIpFp2NCT5oYNHyzCR5v86wB8xM',
    appId: '1:788870623427:ios:019e21f896efcdd9d07276',
    messagingSenderId: '788870623427',
    projectId: 'bionicbean0',
    storageBucket: 'bionicbean0.appspot.com',
    iosBundleId: 'com.example.beanApp0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQRnjVLgsF3y8oqnXOFJqTjus7E6bn8wM',
    appId: '1:788870623427:web:8907493480385b2ed07276',
    messagingSenderId: '788870623427',
    projectId: 'bionicbean0',
    authDomain: 'bionicbean0.firebaseapp.com',
    storageBucket: 'bionicbean0.appspot.com',
    measurementId: 'G-M0XCVWFQQB',
  );

}